import type { NextPage } from 'next';
import Image from 'next/image';
import Layout from '../components/layout';
import styled from 'styled-components';
import Button from '../components/button';
import Section from '../components/section';
import BREAKPOINTS from '../constants';
import TypeformLink from '../components/typeform-link';
import benefitIcons from '../public/images/benefits-icons.svg';
import tradArch from '../public/images/traditional-web-architecture.svg';
import decoupledArch from '../public/images/decoupled-web-architecture.svg';
import checkIcon from '../public/images/check-circle.svg';
import bracket from '../public/images/bracket.svg';

const Home: NextPage = () => {
  return (
    <Layout title='Webjeb Studios | Jamstack Website Experts' layoutGrid='off'>
      <Section id='hero' customStyles={HeroStyles}>
        <HeroContainer>
          <div className='hero-block'>
            <h1>Harness the power of the modern web</h1>
            <p>
              Leverage the latest in web tech to build a faster, more secure
              website that drives your business forward.
            </p>
            <Button
              href='#discover'
              variant='secondary'
              styles={{ marginRight: '2rem', marginBottom: '2rem' }}
            >
              Discover how
            </Button>
            <Button href='#' variant='typeform'>
              Work with us
            </Button>
          </div>
          <BenefitsContainer>
            <div className='icons'>
              <Image
                src={benefitIcons}
                alt='The benefits of a modern website'
              />
            </div>
            <div className='blurb'>
              <h3>Fast</h3>
              <p>
                We build the fastest websites on the web using pre-built pages
                stored on content delivery networks (CDNs) spread across the
                globe.
              </p>
            </div>
            <div className='blurb'>
              <h3>Simple</h3>
              <p>
                Static sites make hosting, maintenance, and security simple.
                Your site scales automatically as your audience grows.
              </p>
            </div>
            <div className='blurb'>
              <h3>Secure</h3>
              <p>
                Your site is statically rendered instead of generated by a
                server. With server requests eliminated, you're less vulnerable
                to attacks.
              </p>
            </div>
          </BenefitsContainer>
        </HeroContainer>
      </Section>
      <Section id='discover' customStyles={DiscoverStyles}>
        <DiscoverContainer>
          <div className='part1'>
            <h2>Are you building on old architecture?</h2>
            <p className='emphasis'>
              In today's crowded and rapidly changing web, your site needs to be
              flexible and nimble to stand out from the pack.
            </p>
            <p className='body'>
              Traditional content management systems (CMS) like Wordpress,
              Drupal, Wix, and Squarespace have been around since the early
              2000's. They use a web architecture where content and display are
              managed together in a single application. This makes them
              convenient but limited. Plugins can extend functionality, but this
              adds complexity, introduces more security risk, and requires more
              effort to maintain.
            </p>
          </div>
          <div className='part1-graphic'>
            <Image src={tradArch} alt='Traditional Web Architecture' />
          </div>
          <div className='part2-graphic'>
            <Image src={decoupledArch} alt='Decoupled Web Architecture' />
          </div>
          <div className='part2'>
            <h2>The future of the web is decoupled</h2>
            <p className='emphasis'>
              A new decoupled approach has emerged and it is changing the way we
              think about and build websites.
            </p>
            <p className='body'>
              In a decoupled system, content is separate from display. This
              allows you to choose the “best in breed” solution for each
              component of your website. This is akin to having a hand-picked
              team of specialists working in concert together, each performing
              their own task with the highest degree of competancy. Because
              decoupled websites are highly optimized, the costs to maintain,
              secure, and scale are much lower than traditional CMS solutions.
            </p>
          </div>
          <div className='part3'>
            <h2>The Jamstack revolution</h2>
            <p className='body'>
              The name given to this decoupled approach is the Jamstack.
              Jamstack stands for Javascript, APIs, and Markup. These three
              terms represent the major components of a Jamstack website.
              Javascript handles the dynamic functionality, APIs provide access
              to the CMS and business logic, and Markup represents the user
              interface which is compiled at build time and served statically
              via CDN.
            </p>
            <h3>The benefits of Jamstack</h3>
            <p className='body'>
              The benefits of Jamstack are undeniably impressive: better
              performance, lock-tight security, unlimited flexibility and
              scalability, portability, and maintainability. Not only that, but
              a traditional CMS like Wordpress (or any CMS) can still be part of
              the solution. The Jamstack approach isn't right for every
              situation, but if your needs extend beyond a simple blog or
              landing page style site, then Jamstack could be a game-changer for
              you.
            </p>
          </div>
          <div className='part3-aside'>
            <p className='emphasis'>
              The benefits of Jamstack are undeniably impressive: better
              performance, lock-tight security, unlimited flexibility and
              scalability, portability, and maintainability.
            </p>
          </div>
        </DiscoverContainer>
      </Section>
      <Section id='bottom-line' customStyles={BottomLineStyles}>
        <BottomLineContainer>
          <div className='heading'>
            <h2>The Bottom Line</h2>
            <h3>What can Jamstack do for you?</h3>
          </div>
          <div className='icon'>
            <Image src={checkIcon} alt='Checkmark' />
          </div>
          <div className='blurb'>
            <h3>Rank higher</h3>
            <p>
              Outpace the competition in time to first byte and other core web
              vitals that Google uses to rank search results. Own one of the
              fastest sites on the web.
            </p>
          </div>
          <div className='icon'>
            <Image src={checkIcon} alt='Checkmark' />
          </div>
          <div className='blurb'>
            <h3>Boost conversions</h3>
            <p>
              Increase user satisfaction and time on your site with higher user
              interactivity. More user engagement leads to more conversions.
            </p>
          </div>
          <div className='icon'>
            <Image src={checkIcon} alt='Checkmark' />
          </div>
          <div className='blurb'>
            <h3>Scale without limits</h3>
            <p>
              Your site is delivered over a CDN with no traffic limits. Your
              site scales automatically, so large spikes in traffic won't crash
              your server.
            </p>
          </div>
          <div className='icon'>
            <Image src={checkIcon} alt='Checkmark' />
          </div>
          <div className='blurb'>
            <h3>Lower maintenance cost</h3>
            <p>
              Jamstack sites are pre-generated so they are simple to host and
              maintain. No constant plugin and software updates to make sure
              your site stays secure.
            </p>
          </div>
        </BottomLineContainer>
      </Section>
      <Section id='about' customStyles={GrayBackground}>
        <AboutContainer>
          <div className='heading'>
            <h2>Introducing Webjeb Studios</h2>
            <div className='experts'>
              <div className='bracket'>
                <Image src={bracket} alt='Bracket' />
              </div>
              <div>
                <h3>We're experts in Jamstack development</h3>
                <p>
                  We've embraced the modern tools and technologies that are
                  making a better web possible today. We're passionate about
                  working together with our clients to unlock their full
                  potential with the Jamstack.
                </p>
              </div>
              <div className='bracket flipped'>
                <Image src={bracket} alt='Bracket' />
              </div>
            </div>
          </div>
          <div className='blurb'>
            <h3>Leadership</h3>
            <p>
              Our team is led by our founder and CEO, James Bryan. James built
              his first website in 1994 and has been doing it ever since! He's
              also a dedicated husband, dad, engineer, pilot, and guitar
              aficianado.
            </p>
          </div>
          <div className='blurb'>
            <h3>Team</h3>
            <p>
              We're a small but mighty team. James manages the projects and his
              wife, Lisa, oversees the day-to-day. We employ a network of web
              professionals, each in their own area of expertise. Seasoned
              pup-professionals, Hannah and Hebert, keep up team morale.
            </p>
          </div>
          <div className='blurb span2'>
            <h3>Oklahoma Proud</h3>
            <p>
              We serve clients all over the world from our home base in Edmond,
              OK. But we particularly enjoy serving our local Oklahomans! We're
              a proud Oklahoma-owned business. If you're in the OKC metro, let's
              connect over coffee!
            </p>
          </div>
        </AboutContainer>
      </Section>
      <Section id='services'>
        <ServicesContainer>
          <h2>Services</h2>
          <div className='blurb span3'>
            <h3>Strategy</h3>
            <p>
              We help you develop a Jamstack strategy and hand pick the best
              tools and services for your project.
            </p>
          </div>
          <div className='blurb'>
            <h3>Analytics</h3>
            <p>
              We provide a simple to use and privacy-focused analytics solution
              made for the decoupled web.
            </p>
          </div>
          <div className='blurb span3'>
            <h3>Design</h3>
            <p>
              We use modern design frameworks coupled with foundational design
              principles to create striking designs that are lightning fast and
              effective.
            </p>
          </div>
          <div className='blurb'>
            <h3>Development</h3>
            <p>
              We solve development challenges with out-of-the-box thinking and
              an unwavering committment to quality.
            </p>
          </div>
          <div className='blurb span3'>
            <h3>SEO</h3>
            <p>
              Jamstack is already a big win for search engine optimization
              (SEO). We help you take it a step further with SEO-specific
              improvements designed to boost traffic and increase engagement.
            </p>
          </div>
          <div className='blurb'>
            <h3>Management</h3>
            <p>
              Protect your investment with our website management services. We
              offer hosting, uptime monitoring, backups, disaster recovery,
              monthly content updates, prioritized service, and more.
            </p>
          </div>
        </ServicesContainer>
      </Section>
      <Section id='pricing'>
        <PricingContainer>
          <h2>Packages & Pricing</h2>
          <div className='package-desc'>
            <p>
              No matter your experience level with Jamstack, we have a package
              for you. Each package starts at the price shown and is customized
              to your specific requirements.
            </p>
            <p>
              Are you a web agency looking to partner with us to deliver
              Jamstack solutions? We have whitelabel packages too.{' '}
              <TypeformLink href='#' id='As7KOBMB'>
                Contact us
              </TypeformLink>{' '}
              for more details.
            </p>
          </div>
          <div className='blurb'>
            <h3>Jamstack Starter</h3>
            <p>
              Choose your CMS and pair it with one of our handcrafted design
              templates. For clients new to the Jamstack game and looking to get
              up and running quickly.
            </p>
          </div>
          <div className='price'>
            <h3 className='emphasis'>Starting at $5,900</h3>
          </div>
          <div className='blurb'>
            <h3>Jamstack Conversion</h3>
            <p>
              Decouple your existing traditional website. We carry over all
              content and keep the design consistent. For clients happy with
              their look and feel but wanting to tap into the power of the
              Jamstack.
            </p>
          </div>
          <div className='price'>
            <h3 className='emphasis'>Starting at $7,900</h3>
          </div>
          <div className='blurb'>
            <h3>Jamstack Ultimate</h3>
            <p>
              A customized solution from the ground up. Includes tech strategy,
              design, development, and SEO. For clients wanting a custom
              solution tailored to their unique business needs.
            </p>
          </div>
          <div className='price'>
            <h3 className='emphasis'>Starting at $12,900</h3>
          </div>
        </PricingContainer>
      </Section>
      <Section id='process' customStyles={GrayBackground}>
        <ProcessContainer>
          <div className='heading'>
            <h2>How it works</h2>
          </div>
          <div className='blurb'>
            <h3>Discover</h3>
            <p>
              This phase is all about you. We learn the ins and outs of your
              business and define your needs. Then we develop a solution and a
              roadmap to accomplish your goals.
            </p>
          </div>
          <div className='blurb'>
            <h3>Design & Develop</h3>
            <p>
              This phase is all about implementation and execution. We take what
              we learned in the discovery phase and deliver the solution with
              speed and quality.
            </p>
          </div>
          <div className='blurb span2'>
            <h3>Refine & Launch</h3>
            <p>
              This phase is all about your satisfaction. We refine based on your
              feedback and then, with our patented launch checklist in hand, we
              take your site live.
            </p>
          </div>
        </ProcessContainer>
      </Section>
      <Section id='work'>
        <WorkContainer>
          <h2>Recent Work</h2>
          <div className='blurb'>
            <h3>Arculum Computers</h3>
            <p>
              A budding custom PC builder needed a fast and effective website to
              stand out from their competition. This is the result.
            </p>
          </div>
          <div className='blurb'>
            <h3>Mark Bryan Construction</h3>
            <p>
              A trusted name in the local communtity for over three decades,
              this residential remodeling company needed to take their brand to
              the next level.
            </p>
          </div>
        </WorkContainer>
      </Section>
      <Section id='cta' customStyles={GrayBackground}>
        <CTAContainer>
          <h2>
            Ready to leverage the power of the Jamstack to grow your business?
          </h2>
          <h3>Don't let the revolution pass you by</h3>
          <p>
            Beat your competition to the punch - be the first to join the
            Jamstack revolution and start reaping the benefits before they do.
          </p>
          <Button href='#' variant='typeform'>
            Work with us
          </Button>
        </CTAContainer>
      </Section>
      <Section id='resources'>
        <ResourcesContainer>
          <div className='heading'>
            <h2>
              Helpful Resources
              <ComingSoon style={{ marginLeft: '1rem' }}>
                Coming Soon
              </ComingSoon>
            </h2>
            <p>
              Check out these helpful resources to learn more about how Jamstack
              and Webjeb Studios can unleash the full potential of your
              business.
            </p>
          </div>
          <div className='blurb'>
            <h3>Jamstack Flowchart</h3>
            <p>
              Can't decide if Jamstack is for you? This flowchart will help.
            </p>
          </div>
          <div className='blurb'>
            <h3>Jamstack Dictionary</h3>
            <p>
              There's a lot of lingo floating around in the Jamstack world. This
              resource will have you speaking the language in no time.
            </p>
          </div>
          <div className='blurb span2'>
            <h3>Jamstack Cost-Benefit Analysis</h3>
            <p>
              See how the Jamstack approach stacks up compared to the
              traditional CMS approach.
            </p>
          </div>
        </ResourcesContainer>
      </Section>
      <Section id='blog'>
        <BlogContainer>
          <div className='heading'>
            <h2>From our blog</h2>
            <p>Musings about Jamstack and the decoupled web.</p>
            <ComingSoon>Coming Soon</ComingSoon>
          </div>
          <div className='blurb'>
            <h3>Fun with Frontend Frameworks</h3>
            <p>
              There are a number of options when it comes to frontend
              frameworks. We tell you which one we use and why.
            </p>
          </div>
          <div className='blurb'>
            <h3>Headless CMS Roundup</h3>
            <p>
              We take a look at all of the headless CMS options currently
              available and discuss the pros and cons of each.
            </p>
          </div>
          <div className='blurb'>
            <h3>The Static Rendering Carousel</h3>
            <p>
              SSG, CSR, SSR, ISR - What does it all mean? We review the
              different methods for static site rendering and when and where to
              use each one.
            </p>
          </div>
        </BlogContainer>
      </Section>
    </Layout>
  );
};

export default Home;

const GrayBackground = {
  backgroundColor: 'var(--color-ltgray-background)',
};

const ComingSoon = styled.span`
  background-color: var(--color-ltgray-background);
  color: var(--color-secondary);
  font-family: var(--font-body);
  font-size: 1.4rem;
  font-weight: 700;
  text-transform: uppercase;
  padding: 1rem;
`;

const HeroStyles = {
  backgroundColor: 'var(--color-text-headings)',
  padding: 0,
};

const HeroContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  background-image: url(../images/hero-circles.svg);
  background-repeat: no-repeat;
  background-position: top 0 right 0;
  margin-right: calc(-1 * var(--document-padding));
  padding-right: var(--document-padding);

  .hero-block {
    grid-column: 1 / -1;
    max-width: 537px;
    margin-top: 110px;
    color: var(--color-text-body-dark);
    h1 {
      color: var(--color-text-headings-dark);
    }
  }

  @media (max-width: ${BREAKPOINTS.xlarge}) {
    background-position: top 0 right -200px;
  }

  @media (max-width: ${BREAKPOINTS.large}) {
    background-position: top 0 right -400px;
  }

  @media (max-width: ${BREAKPOINTS.medium}) {
    background: none;
  }

  @media (max-width: ${BREAKPOINTS.xsmall}) {
    grid-template-columns: 1fr;
    .hero-block {
      grid-column: 1 / -1;
      max-width: 100%;
    }
  }
`;

const BenefitsContainer = styled.div`
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-template-rows: repeat(3, 166px);
  grid-gap: var(--gutter-width);
  margin-top: 184px;
  padding-bottom: 88px;
  color: var(--color-text-body-dark);

  h3 {
    color: var(--color-text-headings-dark);
  }

  div.icons {
    grid-row: 1 / span 3;
  }

  div.blurb {
    grid-column: 2 / span 3;
  }

  @media (max-width: ${BREAKPOINTS.large}) {
    margin-top: var(--document-margin);
    div.icons {
      min-width: 120px;
    }
    div.blurb {
      grid-column: 2 / span 4;
    }
  }

  @media (max-width: ${BREAKPOINTS.small}) {
    div.icons {
      display: none;
    }
    div.blurb {
      grid-column: 1 / -1;
    }
  }
`;

const DiscoverStyles = {
  padding: 0,
};

const DiscoverContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  grid-row-gap: 0;
  background: linear-gradient(
    90deg,
    var(--color-light-background) calc(50% - 3px),
    var(--color-mdgray-background) calc(50% - 3px),
    var(--color-mdgray-background) calc(50% + 3px),
    var(--color-light-background) calc(50% + 3px)
  );

  .body {
    max-width: 60ch;
  }

  .part1 {
    grid-column: 1 / span 6;
    .emphasis {
      max-width: 794px;
    }
    background-color: var(--color-mdgray-background);
    padding: var(--section-padding) var(--document-padding)
      var(--section-padding) var(--section-padding);
    margin: calc(var(--document-margin) * -1) calc(var(--column-width) / 2) 0
      calc(var(--section-padding) * -1);
  }

  .part1-graphic {
    grid-column: 7 / span 2;
    padding-top: var(--document-margin);
  }

  .part2 {
    grid-column: 4 / -1;
    margin: var(--section-padding) 0 var(--section-padding) 0;
    padding: var(--document-padding) 0;
    background-color: var(--color-light-background);

    .emphasis {
      max-width: 717px;
    }

    .body {
      margin-bottom: 0;
    }
  }

  .part2-graphic {
    grid-column: 1 / span 2;
    margin-top: var(--section-padding);
    padding-top: var(--document-padding);
  }

  .part3 {
    grid-column: 1 / span 5;
    padding: var(--section-padding) var(--document-padding)
      var(--section-padding) var(--section-padding);
    margin: 0 calc((var(--column-width) / 2 + var(--gutter-width)) * -1)
      calc(var(--section-padding) * 2) calc(var(--section-padding) * -1);
    background-color: var(--color-dark-background);
    color: var(--color-text-body-dark);
    h2,
    h3 {
      color: var(--color-text-headings-dark);
    }
    p {
      margin-bottom: var(--document-margin);
    }
    p:last-child {
      margin-bottom: 0;
    }
  }

  .part3-aside {
    grid-column: 6 / span 3;
    margin-top: 8.5rem;
    p {
      background-color: var(--color-mdgray-background);
      padding: var(--document-padding);
      margin-left: calc((var(--column-width) / 2 + var(--gutter-width)) * -1);
    }
  }

  @media (max-width: ${BREAKPOINTS.large}) {
    grid-template-columns: 1fr 1fr;

    .part1 {
      grid-column: 1 / -1;
      margin-right: calc(var(--document-padding) * -1);
      padding-right: var(--document-padding);
    }
    .part1-graphic {
      grid-column: 1;
      justify-self: center;
    }
    .part2-graphic {
      grid-column: 2;
      align-self: center;
      justify-self: center;
      margin-top: 0;
      padding-top: var(--document-margin);
    }
    .part2 {
      grid-column: 1 / -1;
    }
    .part3 {
      grid-column: 1 / -1;
      margin-right: calc(var(--document-padding) * -1);
    }
    .part3-aside {
      display: none;
    }
  }

  @media (max-width: ${BREAKPOINTS.medium}) {
    grid-template-columns: 1fr;
    background: none;
    .part1,
    .part1-graphic,
    .part2,
    .part2-graphic,
    .part3,
    .aside {
      grid-column: 1 / -1;
    }
    .part2 {
      padding-bottom: var(--document-padding);
    }
    .part2-graphic {
      order: 2;
      padding-top: 0;
    }
    .part3 {
      order: 3;
      margin-top: var(--section-padding);
      p {
        :last-child {
          margin-bottom: 0;
        }
      }
    }
  }

  @media (max-width: ${BREAKPOINTS.small}) {
    .part1-graphic,
    .part2-graphic {
      max-width: 250px;
    }
  }
`;

const BottomLineStyles = {
  paddingTop: 'var(--document-padding)',
};

const BottomLineContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);

  p {
    max-width: 40ch;
  }

  .heading {
    grid-column: 1 / -1;
    text-align: center;
    margin-bottom: var(--section-padding);
  }

  .icon {
    justify-self: right;
  }

  .blurb {
    grid-column: span 3;
    p {
      margin-bottom: var(--document-margin);
    }
  }

  @media (max-width: ${BREAKPOINTS.medium}) {
    grid-template-columns: 10% 1fr;

    p {
      max-width: 60ch;
    }

    .heading {
      grid-column: 1 / -1;
    }

    .icon {
      width: 20px;
    }

    .blurb {
      grid-column: span 1;
      margin-right: 10%;
    }
  }
`;

const AboutContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);

  .heading {
    grid-column: 1 / -1;
    justify-self: center;
    text-align: center;

    h2 {
      margin-top: var(--document-margin);
      margin-bottom: var(--section-padding);
    }

    p {
      margin: auto;
      max-width: 60ch;
    }

    .experts {
      display: flex;
      align-items: center;
      margin-bottom: var(--section-padding);
    }

    .bracket {
      margin: 0 var(--document-margin);
    }

    .flipped {
      transform: scaleX(-1);
    }
  }

  .blurb {
    grid-column: span 3;
    p {
      max-width: 29ch;
    }
  }

  .span2 {
    grid-column: span 2;
  }

  @media (max-width: ${BREAKPOINTS.large}) {
    .bracket {
      transform: scale(0.7);
    }

    .flipped {
      transform: scaleX(-1) scale(0.7) !important;
    }
  }

  @media (max-width: ${BREAKPOINTS.medium}) {
    grid-template-columns: 1fr;

    .blurb {
      grid-column: 1 / -1;
      p {
        max-width: 60ch;
      }
    }

    .bracket {
      display: none;
    }
  }
`;

const ServicesContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  margin-top: var(--document-margin);

  h2 {
    grid-column: 1 / span 3;
    grid-row: 1 / span 3;
  }

  .blurb {
    grid-column: span 2;
    max-width: 309px;
    margin-bottom: var(--document-margin);

    :last-child,
    :nth-last-child(2) {
      margin-bottom: 0;
    }
  }

  .span3 {
    grid-column: span 3;
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    h2 {
      grid-column: 1 / -1;
      margin-bottom: var(--section-padding);
    }

    .blurb {
      grid-column: span 4;
    }
  }
`;

const PricingContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);

  h2 {
    grid-column: 1 / -1;
  }

  .package-desc {
    grid-column: 1 / span 3;
    grid-row: 2 / span 3;
    font-style: italic;
    max-width: 65ch;
  }

  .blurb {
    grid-column: 4 / span 3;
    p {
      max-width: 40ch;
    }
    margin-bottom: var(--document-margin);
  }

  .price {
    grid-column: 7 / span 2;
    text-align: right;
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    .package-desc {
      grid-column: 1 / -1;
      max-width: 80ch;
      margin-bottom: var(--document-margin);
    }

    .blurb {
      grid-column: 1 / span 5;
    }

    .price {
      grid-column: 6 / span 3;
    }
  }
`;

const ProcessContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);

  .heading {
    grid-column: 1 / -1;
    justify-self: center;
    text-align: center;
    margin-top: var(--document-padding);
    margin-bottom: var(--document-margin);
  }

  .blurb {
    grid-column: span 3;
    p {
      max-width: 33ch;
    }
  }

  .span2 {
    grid-column: span 2;
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    grid-template-columns: 1fr;

    .blurb {
      grid-column: 1 / -1;
      p {
        max-width: 60ch;
      }
    }
  }
`;

const WorkContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  margin-top: var(--document-margin);
  margin-bottom: var(--document-margin);

  h2 {
    grid-column: 1 / span 3;
  }

  .blurb {
    grid-column: 4 / span 4;
    p {
      max-width: 42ch;
    }
    margin-bottom: var(--document-padding);
    :last-child {
      margin-bottom: 0;
    }
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    h2 {
      grid-column: 1 / -1;
      margin-bottom: var(--section-padding);
    }
    .blurb {
      grid-column: 1 / -1;
      p {
        max-width: 60ch;
      }
    }
  }
`;

const CTAContainer = styled.div`
  display: grid;
  justify-items: center;
  text-align: center;
  h2 {
    max-width: 30ch;
    margin-bottom: var(--document-margin);
  }
  p {
    max-width: 60ch;
    margin-bottom: var(--document-margin);
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    margin-top: var(--document-margin);
    margin-bottom: var(--document-margin);
  }
`;

const ResourcesContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  margin-top: var(--document-margin);

  .heading {
    grid-column: 1 / -1;
    justify-self: center;
    text-align: center;
    p {
      max-width: 60ch;
      margin-bottom: var(--section-padding);
    }
  }

  .blurb {
    grid-column: span 3;
    p {
      max-width: 30ch;
    }
    opacity: 0.25;
  }

  .span2 {
    grid-column: span 2;
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    grid-template-columns: 1fr;
    .blurb {
      grid-column: 1 / -1;
      p {
        max-width: 60ch;
      }
    }
  }
`;

const BlogContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-gap: var(--gutter-width);
  margin-bottom: var(--document-margin);

  .heading {
    grid-column: 1 / span 2;
  }

  .blurb {
    grid-column: 4 / span 5;
    p {
      max-width: 40ch;
    }
    opacity: 0.25;
  }

  @media (max-width: ${BREAKPOINTS.tablet}) {
    grid-template-columns: 1fr;
    .heading {
      grid-column: 1 / -1;
      text-align: center;
      p {
        max-width: 100%;
      }
      margin-bottom: var(--document-margin);
    }
    .blurb {
      grid-column: 1 / -1;
      p {
        max-width: 60ch;
      }
    }
  }
`;
