import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Webjeb Studios - Next Version!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>Header</header>
      <main>Main</main>
      <footer>Footer</footer>
    </>
  );
};

export default Home;
